# Generated by Django 4.2.1 on 2023-06-06 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='date_fotografia',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
