# Generated by Django 4.2.1 on 2023-06-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotografia_date_fotografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='photo',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
